apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-prp0-hsr-interface
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/NetworkManager/system-connections/prp0.nmconnection
          mode: 0600
          overwrite: true
          contents:
            source: data:;base64,W2Nvbm5lY3Rpb25dCmlkPXBycDAKdXVpZD01YzQ5Zjg5Mi02NzNhLTRjYzQtOWZmMC1iZGU1NDk2MDAyYjMKdHlwZT1oc3IKaW50ZXJmYWNlLW5hbWU9cHJwMAoKW2hzcl0KcG9ydDE9ZW5wN3MwCnBvcnQyPWVucDhzMApwcnA9dHJ1ZQoKW2lwdjRdCmFkZHJlc3MxPTEwLjEwLjEwLjEvMjQKbWV0aG9kPW1hbnVhbAoKW2lwdjZdCmFkZHItZ2VuLW1vZGU9ZGVmYXVsdAptZXRob2Q9ZGlzYWJsZWQKCltwcm94eV0K
